
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AccesoBD2
{

using System;
    using System.Collections.Generic;
    
public partial class Ingrediente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ingrediente()
    {

        this.Receta = new HashSet<Receta>();

    }


    public int Id { get; set; }

    public string nombre { get; set; }

    public int cantidad { get; set; }

    public string peso { get; set; }

    public double costoPorUnidad { get; set; }

    public string unidad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Receta> Receta { get; set; }

}

}
