//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBD2
{
    using System;
    
    public partial class MostrarCantidadProvisionesPedido_Result1
    {
        public Nullable<int> Id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activado { get; set; }
        public string restricciones { get; set; }
        public Nullable<int> Provision_Id { get; set; }
        public Nullable<int> Categoria_Id { get; set; }
        public int Id1 { get; set; }
        public string nombre { get; set; }
        public int noExistencias { get; set; }
        public string ubicacion { get; set; }
        public int stockMinimo { get; set; }
        public double costoUnitario { get; set; }
        public string unidadMedida { get; set; }
        public bool activado1 { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int Pedido_Id { get; set; }
        public string categoria { get; set; }
    }
}
